services:
  - type: web
    name: epsilon-fm
    env: python
    plan: free
    pythonVersion: 3.12.3  # or latest available
    buildCommand: |
      cd backend
      poetry install
    startCommand: |
      cd backend
      poetry run uvicorn src.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SUPABASE_URL
        value: https://vxihempvdjcfpejmqhbo.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aWhlbXB2ZGpjZnBlam1xaGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzA1NDgsImV4cCI6MjA2NDQwNjU0OH0.naQOjhahITI3PLeR_VYxLSL_IZ82tpcrx4ePHkuJpl0
